development:
  consumer_key: 'your_development_consumer_key'
  consumer_secret: 'your_development_consumer_secret'
  access_token: 'your_development_access_token'
  access_token_secret: 'your_development_access_token_secret'

test: 
  consumer_key: 'your_development_consumer_key'
  consumer_secret: 'your_development_consumer_secret'
  access_token: 'your_development_access_token'
  access_token_secret: 'your_development_access_token_secret'

production:
  consumer_key: 'your_development_consumer_key'
  consumer_secret: 'your_development_consumer_secret'
  access_token: 'your_development_access_token'
  access_token_secret: 'your_development_access_token_secret'